version: '3.9'
services:
  app:
    image: europe-west1-docker.pkg.dev/boost-medium/boost-medium-repo/boost-medium-docker:latest
    build: .
    ports:
      - "8000:8000"
    environment :
      - PORT=8000
    volumes:
      - .:/boost_medium
      - ./requirements.txt:/boost_medium/requirements.txt
    env_file:
      - .env
